apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: statsd-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: statsd-exporter
    spec: 
      containers:
      - name: statsd-exporter
        image: prom/statsd-exporter:latest
        ports:
          - containerPort: 9125
            protocol: TCP
            name: statsd-in
          - containerPort: 9102
            protocol: TCP
            name: prom-out

---
kind: Service
apiVersion: v1
metadata:
  name: statsd-exporter
spec:
  type: LoadBalancer
  ports:
  - name: statsd-in
    port: 9125
    targetPort: 9125
  - name: prom-out
    port: 9102
    targetPort: 9102
  selector:
    app: statsd-exporter
